name: CICD

on:
  workflow_dispatch:
  schedule:
    - cron: "0 03 * * *"
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout source code
      - uses: actions/checkout@v2

      # Login to docker hub using secrets in GitHub.
      - name: Login to docker
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm/v7
          push: true
          tags: kvalitetsit/busykit:latest

#      - name: Build
#        run: ./build/build.sh ${{ env.DOCKER_SERVICE }}:latest
#
#      - name: Push latest service docker image
#        run: ./build/docker-push.sh ${{ env.DOCKER_SERVICE }}:latest